### ISSUE TITLE
Make pls unity3d package 

### ISSUE THREAD

**Issue by achooley** [SlashGames/slash-framework#27]
I had some problem with building dll for using in Unity, Can you pls make build and add to release

**Comment by coeing** [comment]
Hey @chuleiO,
Thanks for the issue. I had a script in place already some time ago (Tools/Build/BuildUnityPackage.bat), but I have to check if it still works. I'll probably have time for it on Saturday.

**Comment by achooley** [comment]
Thx for answer. In script I saw dependency of several PATH variables (unity3d and slash framework).
And if you some time for compare: look into [(https://github.com/sschmid/Entitas-CSharp])  What you think about this library?

**Comment by coeing** [comment]
Hey @chuleiO 
I already had a look at Entitas after I met the devs at the Unite last year in Amsterdam :) They have a similar mindset like we have, so we agreed in many points. They focus on some other parts though, e.g. code generation is a big thing in their architecture. Feel free to check their framework and just use the one that works best for you.

About the issue: I had a look at it and changed the batch file a bit. It should now generate a correct unity package. Furthermore I added a unity package to the releases: https://github.com/SlashGames/slash-framework/releases/tag/v1.0 Let me know if that works for you or if you need anything else to start. Don't hesitate to open new issues :)
