### ISSUE TITLE
How do I persist entities?

### ISSUE THREAD

**Issue by steffenhees** [SlashGames/slash-framework#29]
Could you please give me an example how I could deserialise entites.
Thank you!

**Comment by coeing** [comment]
Hi Steffen!
As we hold all our data inside the components, we basically just have to serialize the entity manager.

First you should serialize all entities with their id and the blueprint they were created from.

Than get all entities from the entity manager. For each entity:
1. Get all properties of their components that may change during runtime
2. Store those properties in an attribute table
3. Serialize the property table with the entity id as a key

When deserializing:
1. Create all entities with their former ids
2. For each entity
- Deserialize the attribute table if it exists
- Init the enity from its blueprint and the attribute table (if it exists)

As I write those lines it sounds like this would be a good feature to be integrated into the framework ;) I will create an issue for this, so we can implement it when there is time.
