### ISSUE TITLE
Lists in AttibuteTables

### ISSUE THREAD

**Issue by steffenhees** [SlashGames/slash-framework#31]
Is there a way to specify Lists in AttibuteTables inside xml Blueprint files e.g. List &lt; Vector2 &gt; ?
(And what about dictionaries ?)

Thanks!

**Comment by steffenhees** [comment]
I found a working solution.
I created a serializable wrapper class containing the list, which I used in the valueType field and value element of the AttributeTable.

**Comment by coeing** [comment]
Right now the standard System.Xml.XmlSerializer is used to serialize/deserialize the attribute tables. It has its shortcomings though as you have realized. 

Lists should work (as long as it is not of an interface or something similar, see http://stackoverflow.com/questions/15722978/i-cant-serialize-a-list-of-objects-in-c-sharp-with-xmlserializer). I tested it with an integer and a Vector2 list, see commit https://github.com/SlashGames/slash-framework/commit/f5e0ded84a3d4482ec7edd65e49f6980c5074707

About dictionaries:
- http://stackoverflow.com/questions/2911514/why-doesnt-xmlserializer-support-dictionary
- http://stackoverflow.com/questions/12554186/how-to-serialize-deserialize-to-dictionaryint-string-from-custom-xml-not-us

**Comment by requistp** [comment]
I'm hitting the same issue, any help along the lines of using List<>s in Components and Blueprints would be appreciated. Thanks!

**Comment by npruehs** [comment]
What kind of issue are facing exactly? Can you elaborate a little more on what you've tried, and what didn't work?

**Comment by requistp** [comment]
Well, I realized that there was a better way to do what I was trying, so the point is moot for now. Still I expect I'll hit this at some point. Here's a test component I built to explain my problem:

[InspectorComponent]
public class TestComponent : IEntityComponent {
    public const string AttributeTest = "Test.Test";

    [InspectorData(AttributeTest)]
    public List<int> IDs { get; set; }

    public void InitComponent(IAttributeTable attributeTable)    {
        IDs = new List<int>();
        // IDs = can data be set here directly from the attribute table? or do I write my own parser?
    }
}

The component shows up[ correctly in the Blueprint builder, but I am unable to add data (pic attached.)

I'm loving the framework, thanks! You guys should refine it a bit and sell it on the asset store!

![blueprinttest](https://cloud.githubusercontent.com/assets/24659212/24125464/16b55c56-0d86-11e7-80b8-509ff13820f2.JPG)

**Comment by coeing** [comment]
@requistp This helps a lot, thanks for posting your test component! I will check it out tomorrow and fix it 👍

**Comment by steffenhees** [comment]
How would this be specified in the xml file, especially the valueType?

Example:
`<Attribute keyType="System.String" valueType="System.Collections.Generic.List[UnityEngine.Vector2]">`
`    <Key>MyComponent.Points</Key>`
`    <Value>`
`        <Points>`
`            <Point>`
`                <x>0</x>`
`                <y>0</y>`
`            </Point>`
`            <Point>`
`                <x>1</x>`
`                <y>2</y>`
`            </Point>`
`        </Points>`
`    </Value>`
`</Attribute>`

**Comment by coeing** [comment]
@requistp The reason it didn't work for you was that you used InspectorData instead of InspectorInt. The code there is not that generic yet, but I refactored how the blueprint editor draws the inspector fields. It uses the real property type now instead of the type of the used attribute.

**Comment by coeing** [comment]
@steffenhees While I was doing the change I also added some code so the blueprint editor draws inspector fields for Vector2, Vector3 and Vector4 properties as well.

The Xml for a Vector2 list would be:

```
<Attribute keyType="System.String" valueType="System.Collections.Generic.List`1[[UnityEngine.Vector2, UnityEngine]]">
  <Key>Test.Vector2</Key>
  <Value xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<Vector2>
	  <x>0</x>
	  <y>0</y>
	</Vector2>
	<Vector2>
	  <x>0</x>
	  <y>0</y>
	</Vector2>
  </Value>
</Attribute>
```

**Comment by requistp** [comment]
Great! Thanks so much for the fast response - again, I'm loving the framework.
