### ISSUE TITLE
References to "strange..." in Slash.Framework.1.2.Unity.5.5

### ISSUE THREAD

**Issue by requistp** [SlashGames/slash-framework#37]
I get errors at numerous places on this release, even after simply importing it into a new project. Example:
![image](https://cloud.githubusercontent.com/assets/24659212/24339391/310b66c0-1260-11e7-9a5a-6c361cd81d8f.png)
 I feel like I'm doing something obviously wrong, but the previous framework simply imported as was ready to go.

Thanks,
Phil

**Comment by npruehs** [comment]
@requistp Sorry, it seems we're missing a reference to StrangeIoC here. Could you verify if including this code helps?

https://github.com/SlashGames/slash-framework/tree/develop/Ext/StrangeIoC/Source

**Comment by coeing** [comment]
@requistp Either what @npruehs suggested or you can delete (not import) the folder **Slash Framework/Slash.Unity.StrangeIoC**. It is an extension when using the StrangeIoC Unity asset (https://www.assetstore.unity3d.com/en/#!/content/9267).
I will make it a separate Unity package this evening, so it won't get imported by default. Thanks for your report 👍

**Comment by requistp** [comment]
First I started a new project and imported the framework and the StrangeIoC from the asset store. There were still errors in ExampleView.cs and UserTileView.cs; I commented out those lines and it compiled. The other option, of simply not importing StrangIoC works as well. Thanks!

**Comment by requistp** [comment]
Actually, I tried again with a fresh install and it did seem to work as is. I believe the first time I didn't tell Unity to replace some APIs it was asking about (sorry, I wasn't paying much attention when the dialog came up.) So I think it works as-is.

**Comment by coeing** [comment]
Okay, good to know. Thanks for checking it and reporting 👍
