### ISSUE TITLE
new install 1.2 for Unity 5.5

### ISSUE THREAD

**Issue by requistp** [SlashGames/slash-framework#38]
I can't tell if/how this is affecting things, but I get this to the console when starting the application:

SpritePacker failed to get types from Slash.Unity.Editor.Common, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null. Error: The classes in the module cannot be loaded.
UnityEditor.Sprites.Packer:GetSelectedPolicyId()

FileNotFoundException: Could not load file or assembly 'Slash.ECS, Version=1.0.6178.27484, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

FileNotFoundException: Could not load file or assembly 'Slash.ECS, Version=1.0.6178.27484, Culture=neutral, PublicKeyToken=null' or one of its dependencies. [I get this one twice]

**Comment by coeing** [comment]
@requistp I will check it later today. Could you check if there is a "Slash Framework\Editor\Slash.Unity.Editor.Common" folder? If so, the Slash.Unity.Editor.Common.dll should be deleted as the editor scripts now come as raw files instead of in a DLL (it's easier to maintain). You can just delete the DLL in that case.

**Comment by coeing** [comment]
Just checked the packages, they don't contain the Slash.Unity.Editor.Common.dll. So it is the one from the previous package and you can just delete it. 
By the way: I just updated the packages, so the StrangeIoC package is not imported by default (https://github.com/SlashGames/slash-framework/releases/tag/v1.2) Thanks for you feedback, it really helps making the usage easier 👍

**Comment by requistp** [comment]
Yes, that worked. Thanks!

**Comment by coeing** [comment]
Great, happy to hear that :)
